import type { Client, Interaction, Property, Reminder } from "./types";
import { CURRENT_USER } from "./constants";

const now = new Date();
const day = (offset: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + offset);
  return d;
};
const hour = (offset: number) => {
  const d = new Date(now);
  d.setHours(d.getHours() + offset);
  return d;
};

export const mockProperties: Property[] = [
  {
    id: "p-001",
    title: "大安森林公園旁 三房兩廳",
    address: "台北市大安區新生南路二段 30 號 8 樓",
    district: "大安區",
    price: 4280,
    type: "買賣",
    rooms: 3,
    bathrooms: 2,
    area: 32,
    floor: "8",
    totalFloors: 14,
    status: "委託中",
    commissionDeadline: day(45),
    description: "近大安森林公園、捷運步行 5 分鐘,屋況極佳,屋主誠售。",
    images: [],
    ownerId: CURRENT_USER.id,
    createdAt: day(-12),
    updatedAt: day(-2),
  },
  {
    id: "p-002",
    title: "信義計畫區 高樓層景觀豪邸",
    address: "台北市信義區松仁路 100 號 28 樓",
    district: "信義區",
    price: 5980,
    type: "買賣",
    rooms: 4,
    bathrooms: 3,
    area: 58,
    floor: "28",
    totalFloors: 32,
    status: "議價中",
    commissionDeadline: day(6),
    description: "面 101 景觀,雙主臥配置,管理優良。",
    images: [],
    ownerId: CURRENT_USER.id,
    createdAt: day(-30),
    updatedAt: day(-1),
  },
  {
    id: "p-003",
    title: "中山國中捷運 2 房美寓",
    address: "台北市中山區復興北路 200 號 5 樓",
    district: "中山區",
    price: 1880,
    type: "買賣",
    rooms: 2,
    bathrooms: 1,
    area: 22,
    floor: "5",
    totalFloors: 7,
    status: "帶看中",
    commissionDeadline: day(20),
    description: "捷運中山國中站旁,生活機能成熟,首購族首選。",
    images: [],
    ownerId: CURRENT_USER.id,
    createdAt: day(-7),
    updatedAt: day(-1),
  },
  {
    id: "p-004",
    title: "內湖科技園區 三房附車位",
    address: "台北市內湖區瑞光路 300 號 12 樓",
    district: "內湖區",
    price: 2680,
    type: "買賣",
    rooms: 3,
    bathrooms: 2,
    area: 38,
    floor: "12",
    totalFloors: 18,
    status: "成交",
    commissionDeadline: day(-15),
    description: "內科商圈,科技新貴最愛,含平面車位。",
    images: [],
    ownerId: CURRENT_USER.id,
    createdAt: day(-60),
    updatedAt: day(-15),
  },
  {
    id: "p-005",
    title: "松山機場旁精緻套房 (出租)",
    address: "台北市松山區敦化北路 88 號 3 樓",
    district: "松山區",
    price: 35,
    type: "租賃",
    rooms: 1,
    bathrooms: 1,
    area: 9,
    floor: "3",
    totalFloors: 12,
    status: "委託中",
    commissionDeadline: day(30),
    description: "全新整理裝潢、家具家電齊全、可短租。",
    images: [],
    ownerId: CURRENT_USER.id,
    createdAt: day(-5),
    updatedAt: day(-1),
  },
  {
    id: "p-006",
    title: "大安老公寓低總價投資物件",
    address: "台北市大安區和平東路三段 50 號 4 樓",
    district: "大安區",
    price: 1380,
    type: "買賣",
    rooms: 2,
    bathrooms: 1,
    area: 18,
    floor: "4",
    totalFloors: 5,
    status: "解除委託",
    commissionDeadline: day(-3),
    description: "屋主降價未果,已解除委託。可作為案例參考。",
    images: [],
    ownerId: CURRENT_USER.id,
    createdAt: day(-90),
    updatedAt: day(-3),
  },
];

export const mockClients: Client[] = [
  {
    id: "c-001",
    name: "王俊傑",
    phone: "0912-111-222",
    lineId: "junjie_w",
    type: "買方",
    status: "追蹤中",
    budgetMin: 2000,
    budgetMax: 3000,
    preferredDistricts: ["中山區", "松山區"],
    requirements: "首購、雙北捷運站 5 分鐘內、2 房以上",
    assignedTo: CURRENT_USER.id,
    lastContactAt: hour(-6),
    createdAt: day(-20),
  },
  {
    id: "c-002",
    name: "林詩涵",
    phone: "0922-333-444",
    lineId: "shihan_l",
    type: "買方",
    status: "帶看",
    budgetMin: 4000,
    budgetMax: 5500,
    preferredDistricts: ["大安區", "信義區"],
    requirements: "三房、坪數 30 以上、景觀優先",
    assignedTo: CURRENT_USER.id,
    lastContactAt: hour(-2),
    createdAt: day(-15),
  },
  {
    id: "c-003",
    name: "陳建宏",
    phone: "0933-555-666",
    type: "賣方",
    status: "議價",
    preferredDistricts: ["信義區"],
    requirements: "希望 5800 萬以上成交,可調整裝潢價",
    assignedTo: CURRENT_USER.id,
    lastContactAt: day(-1),
    createdAt: day(-40),
  },
  {
    id: "c-004",
    name: "黃美玲",
    phone: "0955-777-888",
    lineId: "meiling.h",
    type: "房東",
    status: "成交",
    preferredDistricts: ["松山區"],
    requirements: "短租客為主,租金 35,000 起",
    assignedTo: CURRENT_USER.id,
    lastContactAt: day(-3),
    createdAt: day(-50),
  },
  {
    id: "c-005",
    name: "張育銘",
    phone: "0966-999-000",
    type: "租客",
    status: "新客戶",
    budgetMin: 25,
    budgetMax: 40,
    preferredDistricts: ["松山區", "中山區"],
    requirements: "套房、可短租 6 個月、近捷運",
    assignedTo: CURRENT_USER.id,
    lastContactAt: hour(-12),
    createdAt: day(-1),
  },
  {
    id: "c-006",
    name: "吳怡君",
    phone: "0911-222-333",
    lineId: "yijun_wu",
    type: "買方",
    status: "新客戶",
    budgetMin: 1500,
    budgetMax: 2200,
    preferredDistricts: ["中山區", "內湖區"],
    requirements: "投資型物件、屋齡 30 年內可接受",
    assignedTo: CURRENT_USER.id,
    lastContactAt: hour(-20),
    createdAt: day(-2),
  },
  {
    id: "c-007",
    name: "蔡明哲",
    phone: "0988-444-555",
    type: "賣方",
    status: "流失",
    preferredDistricts: ["大安區"],
    requirements: "屋主已轉委託他家。",
    assignedTo: CURRENT_USER.id,
    lastContactAt: day(-30),
    createdAt: day(-90),
  },
  {
    id: "c-008",
    name: "李玉芬",
    phone: "0977-666-777",
    lineId: "yufen.lee",
    type: "買方",
    status: "追蹤中",
    budgetMin: 3500,
    budgetMax: 4500,
    preferredDistricts: ["大安區", "中山區"],
    requirements: "屋齡 15 年內、三房、需含車位",
    assignedTo: CURRENT_USER.id,
    lastContactAt: hour(-1),
    createdAt: day(-10),
  },
];

export const mockInteractions: Interaction[] = [
  {
    id: "i-001",
    clientId: "c-002",
    propertyId: "p-001",
    type: "帶看",
    note: "客戶對採光與格局滿意,擔心管理費略高。",
    createdBy: CURRENT_USER.id,
    createdAt: hour(-2),
  },
  {
    id: "i-002",
    clientId: "c-001",
    type: "電話",
    note: "更新近期捷運站旁 2-3 房新案,客戶要求週末再帶看一次。",
    createdBy: CURRENT_USER.id,
    createdAt: hour(-6),
  },
  {
    id: "i-003",
    clientId: "c-008",
    type: "LINE",
    note: "提供大安區三房物件清單,客戶請假後回覆。",
    createdBy: CURRENT_USER.id,
    createdAt: hour(-1),
  },
  {
    id: "i-004",
    clientId: "c-003",
    propertyId: "p-002",
    type: "電話",
    note: "屋主希望加價 80 萬,需與買方再溝通。",
    createdBy: CURRENT_USER.id,
    createdAt: day(-1),
  },
  {
    id: "i-005",
    clientId: "c-005",
    type: "LINE",
    note: "新客戶初次接觸,提供租賃需求表。",
    createdBy: CURRENT_USER.id,
    createdAt: hour(-12),
  },
];

export const mockReminders: Reminder[] = [
  {
    id: "r-001",
    type: "委託到期",
    title: "信義計畫區 高樓層景觀豪邸 委託到期",
    targetId: "p-002",
    remindAt: day(6),
    isDone: false,
    createdBy: CURRENT_USER.id,
  },
  {
    id: "r-002",
    type: "追蹤客戶",
    title: "聯繫王俊傑確認週末帶看時段",
    targetId: "c-001",
    remindAt: day(0),
    isDone: false,
    createdBy: CURRENT_USER.id,
  },
  {
    id: "r-003",
    type: "帶看行程",
    title: "下午 3 點 林詩涵 帶看 大安森林公園案",
    targetId: "p-001",
    remindAt: hour(3),
    isDone: false,
    createdBy: CURRENT_USER.id,
  },
  {
    id: "r-004",
    type: "追蹤客戶",
    title: "回覆吳怡君投資型物件清單",
    targetId: "c-006",
    remindAt: day(0),
    isDone: false,
    createdBy: CURRENT_USER.id,
  },
  {
    id: "r-005",
    type: "委託到期",
    title: "大安老公寓物件已過期,需與屋主結案",
    targetId: "p-006",
    remindAt: day(-3),
    isDone: true,
    createdBy: CURRENT_USER.id,
  },
  {
    id: "r-006",
    type: "自訂",
    title: "整理本月帶看紀錄並回報主管",
    remindAt: day(2),
    isDone: false,
    createdBy: CURRENT_USER.id,
  },
];
